baseURL = "https://www.journaldungeek.com/"
languageCode = "fr"
title = "Journal d'un geek"
theme = "hugo-cards"
paginate = 9

[params]
  defaultImage = "gopher.jpg"

  instagram = "https://www.instagram.com/journaldung33k/"
  facebook = "https://www.facebook.com/journaldung33k"
  twitter = "https://twitter.com/journaldung33k"
  email = "thomas@journaldungeek.com"

  fbLikeBox = ""
  fbAppId = ""
  fbPageUrl = "https://www.facebook.com/journaldung33k"
  fbPageTitle = ""

  analytics = "UA-141879724-1"
  disqus = ""

  [params.copyright]
     name = "Thomas CHAUVIN"
     link = "http://www.thomaschauvin.com"
