baseURL = "https://www.journaldungeek.com/"
title = "Journal d'un Geek"
languageCode = "fr"
paginate = 10
theme = "binario"

[Params]
  description = "Journal d'un Geek se veut être un cahier de laboratoire, un journal d'expériences dans lequel je note tout mes essais."
  columns = 2
  mainSections = ["posts"]
  dateFormat = "January 02, 2006"
