baseURL = "https://www.journaldungeek.com/"
languageCode = "fr"
title = "Journal d'un geek"
theme = "hugo-cards"
paginate = 9

[params]
#  builtBy = "bool"
  defaultImage = "gopher.jpg"

  facebook = "journaldung33k"
#  quora = ""
  twitter = "journaldung33k"
#  github = "http://github.com/bul-ikana"
  email = "thomas@journaldungeek.com"

  fbLikeBox = ""
  fbAppId = ""
  fbPageUrl = ""
  fbPageTitle = ""

  analytics = ""
  disqus = ""

  [params.copyright]
     name = "Thomas CHAUVIN"
     link = "http://www.thomaschauvin.com"
